language: php

sudo: false

matrix:
    include:
        - php: 7.2
          env: DOCTRINE="2.5.*"
          env: JMS="1.7.*"
        - php: 7.2
          env: DOCTRINE="2.6.*"
          env: JMS="1.7.*"
        - php: 7.2
          env: DOCTRINE="2.6.*"
          env: JMS="2.1.*"
        - php: 7.3
          env: DOCTRINE="2.6.*"
          env: JMS="2.1.*"

before_install:
  - if [ "$DOCTRINE" != "" ]; then composer require --dev --no-update doctrine/orm=$DOCTRINE; fi
  - if [ "$JMS" != "" ]; then composer require --dev --no-update jms/metadata=$JMS; fi

install:
  - composer update --prefer-dist

script: phpunit
